Kactus\Model\Project:
    type:  entity
    table: projects
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        repoGithub:
            type: string
            length: 255
        createdAt:
            type: datetime
            nullable: false

    manyToOne:
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id

        customer:
          targetEntity: Customer
          inversedBy: projects
          joinColumn:
            name: customer_id
            referencedColumnName: id
